### PR TITLE
PLAT-203 - Aggregate multiple objects

### PR DESCRIPTION
**Pull request by jefmoura**
## Purpose
When a user fetches a list of objects instead of only one, the data mesh needs to be able to expand all data, in other words, the application will aggregate data of all objects from the list.

### CODE REVIEW

**Comment by jefmoura** [comment]
Sorry for the big PR. It's because of the tests

**Comment by ralfzen** [comment]
cf9d8af is an empty commit

**Review by ralfzen — APPROVED** [review]
Finally some tests for Bifrost 🎉

**Review by ralfzen — CHANGES_REQUESTED** [review]
Plz remove cf9d8af

**Comment by jefmoura** [comment]
Just did it @ralfzen

**Review by ralfzen — APPROVED** [review]

**Comment by ralfzen** [comment]
Thanks!

**Pull request merged**
