### PR TITLE
PLAT-160: fix tests for auth and workflow team

### PR DESCRIPTION
**Pull request by docktorrr**
## Purpose
Fix and refactor broken tests

## Approach
* add WorkflowLevel2Sort factory
* old python 2 code -> python 3
* tola_user -> core_user
* update in auth_pipeline (`core_site = CoreSites.objects.get(site=site)` caused 500 when there's no current site). Anyway updating social auth will be a part of another task, so we need these tests to be updated as well (@jefmoura ). 
* removed couple of tests in auth_pipeline (the pipeline)
* removed tests regarding login/registration through a web form (web/tests/test_views.py)
* removed workflow/tests/test_userview.py as we have new tests in registration PR.
* In activity API the relationship between two objects was defined with URL. I changed tests to use primary key instead of URL.
* fix workflow_team tests

Sorry for such a big PR

### CODE REVIEW

**Review by rafa-munoz — APPROVED** [review]
This is the PR that you would give to your enemies 😂I would have split into 2 PRs at least because it's quite big.

I took a quick look and looks fine, but needs a couple of reviews more to be merged. Thanks!

**Comment by docktorrr** [comment]
@Menda Agree, it's only one commit, so it's hard to break it, I realised only after commit, that it's so big. Try to avoid this in future.

**Review by ralfzen — APPROVED** [review]

**Comment by rafa-munoz** [comment]
No problem @docktorrr We are all here to learn and get better. They are just small details because you are doing a great job!

**Comment by ralfzen** [comment]
If everything is working, you can add the tests explicitly to the `.drone` -file.

**Comment by docktorrr** [comment]
@ralfzen More to come :)

**Pull request merged**
