### PR TITLE
clean code to run locally

### PR DESCRIPTION
**Pull request by odenypeter**
## Purpose
- clean code to run locally

## Approach
- add missing imports
- update incompatible packages
- fix broken migrations
- clean models

### CODE REVIEW

**Review by anamariaroman — COMMENTED** [review]
Review check

**Review by anamariaroman — APPROVED** [review]

**Review by hugocortesmu — COMMENTED** [review]
check the pull request

**Review by anamariaroman — APPROVED** [review]
checks pass

**Review by hugocortesmu — APPROVED** [review]
check

**Review by glind — APPROVED** [review]

**Pull request merged**
