### PR TITLE
PLAT-283: pep8 fixes

### PR DESCRIPTION
**Pull request by docktorrr**
## Purpose
Fix code according PEP8, so it could be passed by flake8

## Approach
* Go through code and fix all flake8 messages
* make max line length = 120 chars (see setup.cfg)
* Add flake8 check to drone CI
* (Out of scope) also added `pip install --upgrade pip` to Dockerfile

### CODE REVIEW

**Review by jefmoura — COMMENTED** [review]
Why don't you add the factories folder to `setup.cfg` instead of adding `noqa` in the `__init__.py`?

**Comment by jefmoura** [comment]
Could you also update the Backend guidelines, regarding the 120 line chars?

**Comment by docktorrr** [comment]
> Why don't you add the factories folder to `setup.cfg` instead of adding `noqa` in the `__init__.py`?

@jefmoura But I don't want to exclude the whole factories folder from checking, just these lines of code

**Comment by docktorrr** [comment]
> Could you also update the Backend guidelines, regarding the 120 line chars?

I'll do it, asked for edit permissions

**Comment by jefmoura** [comment]
@docktorrr 
- What's the reason for not including the whole factory folder?
- Don't you said that JSON files could easily break 80 - 120 chars line rule?

**Comment by docktorrr** [comment]
@jefmoura 
But why should we exclude it, it's the python code. I think we should find the reasons not to include it into the check rather then opposite :)
I think the better solution for removing `# noqa` is to change it to explicit import of each factory instead of `*`

**Comment by jefmoura** [comment]
As we talked, we're gonna list all the models in the `init` of factories folder and include the whole folder instead.

**Review by jefmoura — APPROVED** [review]

**Pull request merged**
